// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.22.2
// source: service.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	StringConverter_ToDatabase_FullMethodName = "/StringConverter/ToDatabase"
)

// StringConverterClient is the client API for StringConverter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StringConverterClient interface {
	ToDatabase(ctx context.Context, in *ClientMessage, opts ...grpc.CallOption) (*ServerMessage, error)
}

type stringConverterClient struct {
	cc grpc.ClientConnInterface
}

func NewStringConverterClient(cc grpc.ClientConnInterface) StringConverterClient {
	return &stringConverterClient{cc}
}

func (c *stringConverterClient) ToDatabase(ctx context.Context, in *ClientMessage, opts ...grpc.CallOption) (*ServerMessage, error) {
	out := new(ServerMessage)
	err := c.cc.Invoke(ctx, StringConverter_ToDatabase_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StringConverterServer is the server API for StringConverter service.
// All implementations must embed UnimplementedStringConverterServer
// for forward compatibility
type StringConverterServer interface {
	ToDatabase(context.Context, *ClientMessage) (*ServerMessage, error)
	mustEmbedUnimplementedStringConverterServer()
}

// UnimplementedStringConverterServer must be embedded to have forward compatible implementations.
type UnimplementedStringConverterServer struct {
}

func (UnimplementedStringConverterServer) ToDatabase(context.Context, *ClientMessage) (*ServerMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ToDatabase not implemented")
}
func (UnimplementedStringConverterServer) mustEmbedUnimplementedStringConverterServer() {}

// UnsafeStringConverterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StringConverterServer will
// result in compilation errors.
type UnsafeStringConverterServer interface {
	mustEmbedUnimplementedStringConverterServer()
}

func RegisterStringConverterServer(s grpc.ServiceRegistrar, srv StringConverterServer) {
	s.RegisterService(&StringConverter_ServiceDesc, srv)
}

func _StringConverter_ToDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StringConverterServer).ToDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StringConverter_ToDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StringConverterServer).ToDatabase(ctx, req.(*ClientMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// StringConverter_ServiceDesc is the grpc.ServiceDesc for StringConverter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StringConverter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "StringConverter",
	HandlerType: (*StringConverterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ToDatabase",
			Handler:    _StringConverter_ToDatabase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
