basePath: /api/v1
definitions:
  mseed.MiniSEEDFile:
    properties:
      name:
        type: string
      size:
        type: string
      time:
        type: string
      ttl:
        type: integer
    type: object
  publisher.Geophone:
    properties:
      ehe:
        items:
          type: integer
        type: array
      ehn:
        items:
          type: integer
        type: array
      ehz:
        items:
          type: integer
        type: array
      ts:
        type: integer
    type: object
  publisher.System:
    properties:
      errors:
        type: integer
      failures:
        type: integer
      messages:
        type: integer
      offset:
        type: number
      pushed:
        type: integer
      queued:
        type: integer
    type: object
  response.HttpResponse:
    properties:
      data: {}
      error:
        type: boolean
      message:
        type: string
      path:
        type: string
      status:
        type: integer
      time:
        type: string
    type: object
  station.System:
    properties:
      adc:
        $ref: '#/definitions/station.adcModel'
      cpu:
        $ref: '#/definitions/station.cpuModel'
      disk:
        $ref: '#/definitions/station.diskModel'
      geophone:
        $ref: '#/definitions/station.geophoneModel'
      memory:
        $ref: '#/definitions/station.memoryModel'
      os:
        $ref: '#/definitions/station.osModel'
      position:
        $ref: '#/definitions/station.positionModel'
      station:
        $ref: '#/definitions/station.stationModel'
      status:
        $ref: '#/definitions/publisher.System'
      timestamp:
        type: integer
      uptime:
        type: integer
    type: object
  station.adcModel:
    properties:
      fullscale:
        type: number
      resolution:
        type: integer
    type: object
  station.cpuModel:
    properties:
      model:
        type: string
      percent:
        type: number
    type: object
  station.diskModel:
    properties:
      free:
        type: integer
      percent:
        type: number
      total:
        type: integer
      used:
        type: integer
    type: object
  station.geophoneModel:
    properties:
      ehe:
        type: number
      ehn:
        type: number
      ehz:
        type: number
    type: object
  station.memoryModel:
    properties:
      free:
        type: integer
      percent:
        type: number
      total:
        type: integer
      used:
        type: integer
    type: object
  station.osModel:
    properties:
      arch:
        type: string
      distro:
        type: string
      hostname:
        type: string
      os:
        type: string
    type: object
  station.positionModel:
    properties:
      elevation:
        type: number
      latitude:
        type: number
      longitude:
        type: number
    type: object
  station.stationModel:
    properties:
      location:
        type: string
      name:
        type: string
      network:
        type: string
      station:
        type: string
      uuid:
        type: string
    type: object
  trace.Event:
    properties:
      depth:
        type: number
      distance:
        type: number
      estimation:
        $ref: '#/definitions/trace.estimation'
      event:
        type: string
      latitude:
        type: number
      longitude:
        type: number
      magnitude:
        type: number
      region:
        type: string
      timestamp:
        type: integer
      verfied:
        type: boolean
    type: object
  trace.estimation:
    properties:
      p:
        type: number
      s:
        type: number
    type: object
info:
  contact: {}
  description: This is Observer RESTful API documentation, please set `server_settings.debug`
    to `false` in `config.json` when deploying to production environment in case of
    any security issues.
  title: Observer RESTful API documentation
paths:
  /history:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Get waveform count data in specified time range, channel and format
      parameters:
      - description: Start timestamp of the waveform data to be queried, in milliseconds
        in: formData
        name: start
        required: true
        type: integer
      - description: End timestamp of the waveform data to be queried, in milliseconds
        in: formData
        name: end
        required: true
        type: integer
      - description: Format of the waveform data to be queried, `json` or `sac`
        in: formData
        name: format
        required: true
        type: string
      - description: Channel of the waveform, `EHZ`, `EHE` or `EHN`, reuqired when
          format is `sac`
        in: formData
        name: channel
        type: string
      produces:
      - application/json
      - application/octet-stream
      responses:
        "200":
          description: Successfully exported the waveform data
          schema:
            allOf:
            - $ref: '#/definitions/response.HttpResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/publisher.Geophone'
                  type: array
              type: object
        "400":
          description: Failed to export waveform data due to invalid format or channel
          schema:
            $ref: '#/definitions/response.HttpResponse'
        "410":
          description: Failed to export waveform data due to no data available
          schema:
            $ref: '#/definitions/response.HttpResponse'
        "500":
          description: Failed to export waveform data due to failed to read data source
          schema:
            $ref: '#/definitions/response.HttpResponse'
      summary: Observer waveform history
  /mseed:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: List MiniSEED data if action is `show`, or export MiniSEED data
        in .mseed format if action is `export`
      parameters:
      - description: Action to be performed, either `show` or `export`
        in: formData
        name: action
        required: true
        type: string
      - description: Name of MiniSEED file to be exported, end with `.mseed`
        in: formData
        name: name
        type: string
      produces:
      - application/json
      - application/octet-stream
      responses:
        "200":
          description: Successfully get list of MiniSEED files
          schema:
            allOf:
            - $ref: '#/definitions/response.HttpResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/mseed.MiniSEEDFile'
                  type: array
              type: object
        "400":
          description: Failed to list or export MiniSEED data due to invalid request
            body
          schema:
            $ref: '#/definitions/response.HttpResponse'
        "410":
          description: Failed to export MiniSEED data due to invalid file name or
            permission denied
          schema:
            $ref: '#/definitions/response.HttpResponse'
        "500":
          description: Failed to list or export MiniSEED data due to internal server
            error
          schema:
            $ref: '#/definitions/response.HttpResponse'
      summary: Observer MiniSEED data
  /station:
    get:
      description: Get Observer station status including system information, memory
        usage, disk usage, CPU usage, ADC information, geophone information, and location
        information
      produces:
      - application/json
      responses:
        "200":
          description: Successfully read station status
          schema:
            allOf:
            - $ref: '#/definitions/response.HttpResponse'
            - properties:
                data:
                  $ref: '#/definitions/station.System'
              type: object
      summary: Observer station status
  /trace:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Get list of earthquake events data source and earthquake events
        from specified data source
      parameters:
      - description: Use `show` to get available sources first, then choose one and
          request again to get events
        in: formData
        name: source
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully read the list of earthquake events
          schema:
            allOf:
            - $ref: '#/definitions/response.HttpResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/trace.Event'
                  type: array
              type: object
        "400":
          description: Failed to read earthquake event list due to invalid data source
          schema:
            $ref: '#/definitions/response.HttpResponse'
        "500":
          description: Failed to read earthquake event list due to failed to read
            data source
          schema:
            $ref: '#/definitions/response.HttpResponse'
      summary: Observer event trace
swagger: "2.0"
