name: Build Docker images

on:
    workflow_dispatch:
    push:
        tags:
            - "*"

env:
    REGISTRY: ghcr.io
    ORGANIZATION: anyshake
    PACKAGE: observer

jobs:
    build_docker_image:
        runs-on: ubuntu-latest

        permissions:
            packages: write
            contents: read

        strategy:
            matrix:
                platform:
                    - linux/386
                    - linux/amd64
                    - linux/arm/v6
                    - linux/arm/v7
                    - linux/arm64
                    - linux/ppc64le
                    - linux/riscv64
                    - linux/s390x
            fail-fast: false

        steps:
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18.14.0"

            - name: Checkout source code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 1

            - name: Build frontend
              working-directory: frontend/src
              run: |
                  npm install
                  npm run build

            - name: Docker prepare
              run: |
                  platform=${{ matrix.platform }}
                  echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
                  echo "BUILD_PLATFORMS=${{ strategy.job-total }}" >> $GITHUB_ENV

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.REGISTRY }}/${{ env.ORGANIZATION }}/${{ env.PACKAGE }}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
              with:
                  version: latest
                  driver-opts: "image=moby/buildkit:v0.10.5"

            - name: Login to Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push by digest
              id: build
              uses: docker/build-push-action@v6
              with:
                  provenance: false
                  context: .
                  platforms: ${{ matrix.platform }}
                  labels: ${{ steps.meta.outputs.labels }}
                  outputs: type=image,name=${{ env.REGISTRY }}/${{ env.ORGANIZATION }}/${{ env.PACKAGE }},push-by-digest=true,name-canonical=true,push=true

            - name: Export digest
              run: |
                  mkdir -p /tmp/digests
                  digest="${{ steps.build.outputs.digest }}"
                  touch "/tmp/digests/${digest#sha256:}"

            - name: Upload digest
              uses: actions/upload-artifact@v4
              with:
                  name: digests-${{ env.PLATFORM_PAIR }}
                  path: /tmp/digests/*
                  if-no-files-found: error
                  retention-days: 1

    merge_docker_digests:
        runs-on: ubuntu-latest

        permissions:
            packages: write
            contents: read

        needs:
            - build_docker_image
        steps:
            - name: Download digests
              uses: actions/download-artifact@v4
              with:
                  path: /tmp/digests
                  pattern: digests-*
                  merge-multiple: true

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.REGISTRY }}/${{ env.ORGANIZATION }}/${{ env.PACKAGE }}

            - name: Login to Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Create manifest list and push
              working-directory: /tmp/digests
              run: |
                  docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
                    $(printf '${{ env.REGISTRY }}/${{ env.ORGANIZATION }}/${{ env.PACKAGE }}@sha256:%s ' *)

            - name: Inspect image
              run: |
                  docker buildx imagetools inspect ${{ env.REGISTRY }}/${{ env.ORGANIZATION }}/${{ env.PACKAGE }}:${{ steps.meta.outputs.version }}

            - name: Remove untagged images
              uses: actions/delete-package-versions@v5
              with:
                  package-name: ${{ env.PACKAGE }}
                  package-type: "container"
                  delete-only-untagged-versions: "true"
                  min-versions-to-keep: ${{ env.BUILD_PLATFORMS }}
